#!/bin/sh

DIR=.
APP=demo
CMD=app.js

start() {
	if [ ! -f $DIR/.pid ]; then
		cd $DIR
		/usr/local/bin/node $DIR/$CMD 2>&1 >>$DIR/${APP}.log &
		echo $0 started on $!
	fi
}

stop() {
	if [ -f $DIR/.pid ]; then
		kill $(cat $DIR/.pid)
		echo Application stopped
		rm $DIR/.pid
	fi
}

status() {
	if [ -f $DIR/.pid ]; then
		PID=$(cat $DIR/.pid)
		kill -USR2 $PID && cat "$DIR/.stat" | json
	else
		echo Application is not running
	fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo $"Usage: $prog {start|stop|restart|status|help}"
esac

